UniversalFields:
  Comment: 
    Type: string
  Next:
    Type: State
  End:
    Type: bool
    OutputOnly: true

SharedFields:
  Resource:
    Type: string

StateTypes:
  Task: 
    IncludeFields:
      - Resource
    StateType: "Task"

  DynamoGet:
    StateType: "Task"

  Succeed:
    StateType: "Succeed"

  Fail:
    StateType: "Fail"
